openai_input:
  name: OpenAI input
  description: Send a message to OpenAI
  fields:
    prompt:
      name: Prompt
      description: The message to send
      required: true
      example: "Tell a joke"
      selector:
        text:
          multiline: true

    model:
      name: Model
      advanced: true
      description: The model to use
      required: false
      example: "gpt4hassio"
      default: "gpt4hassio"
      selector:
        select:
          options:
            - "gpt4hassio"
